declare const api: {
    getRectPathD: (props: {
        x: number;
        y: number;
        width: number;
        height: number;
        rx?: number | undefined;
        ry?: number | undefined;
    }) => string;
    createRectPath: (props: {
        document?: Document | undefined;
        x: number;
        y: number;
        width: number;
        height: number;
        rx?: number | undefined;
        ry?: number | undefined;
        id?: string | undefined;
        classes?: string | undefined;
        style?: string | undefined;
        pathLength?: string | number | undefined;
        stroke?: string | undefined;
        strokeWidth?: string | number | undefined;
        strokeOpacity?: string | number | undefined;
        strokeLinecap?: string | undefined;
        strokeLinejoin?: string | undefined;
        strokeDasharray?: string | undefined;
        strokeDashoffset?: string | number | undefined;
        strokeMiterlimit?: string | number | undefined;
        fill?: string | undefined;
        fillOpacity?: string | number | undefined;
        fillRule?: string | undefined;
        filter?: string | undefined;
        mask?: string | undefined;
        transform?: string | undefined;
        vectorEffect?: string | undefined;
        shapeRendering?: string | undefined;
        clipPath?: string | undefined;
        clipRule?: string | undefined;
        opacity?: string | number | undefined;
        visibility?: string | undefined;
    }) => SVGPathElement;
    createStar: (props: {
        document?: Document | undefined;
        raysNumber: number;
        centerX: number;
        centerY: number;
        outerRadius: number;
        innerRadius: number;
        decimalPlaces?: number | undefined;
        id?: string | undefined;
        classes?: string | undefined;
        style?: string | undefined;
        d?: string | undefined;
        pathLength?: string | number | undefined;
        stroke?: string | undefined;
        strokeWidth?: string | number | undefined;
        strokeOpacity?: string | number | undefined;
        strokeLinecap?: string | undefined;
        strokeLinejoin?: string | undefined;
        strokeDasharray?: string | undefined;
        strokeDashoffset?: string | number | undefined;
        strokeMiterlimit?: string | number | undefined;
        fill?: string | undefined;
        fillOpacity?: string | number | undefined;
        fillRule?: string | undefined;
        filter?: string | undefined;
        mask?: string | undefined;
        transform?: string | undefined;
        vectorEffect?: string | undefined;
        shapeRendering?: string | undefined;
        clipPath?: string | undefined;
        clipRule?: string | undefined;
        opacity?: string | number | undefined;
        visibility?: string | undefined;
    }) => SVGPathElement;
    download: (props: {
        $svg?: SVGSVGElement | undefined;
        svgString?: string | undefined;
        outfileName?: string | undefined;
        ext?: string | undefined;
    }) => Promise<{
        isError: boolean;
        msg?: string | undefined;
    }>;
    createPath: (props: {
        document?: Document | undefined;
        id?: string | undefined;
        classes?: string | undefined;
        style?: string | undefined;
        d?: string | undefined;
        pathLength?: string | number | undefined;
        stroke?: string | undefined;
        strokeWidth?: string | number | undefined;
        strokeOpacity?: string | number | undefined;
        strokeLinecap?: string | undefined;
        strokeLinejoin?: string | undefined;
        strokeDasharray?: string | undefined;
        strokeDashoffset?: string | number | undefined;
        strokeMiterlimit?: string | number | undefined;
        fill?: string | undefined;
        fillOpacity?: string | number | undefined;
        fillRule?: string | undefined;
        filter?: string | undefined;
        mask?: string | undefined;
        transform?: string | undefined;
        vectorEffect?: string | undefined;
        shapeRendering?: string | undefined;
        clipPath?: string | undefined;
        clipRule?: string | undefined;
        opacity?: string | number | undefined;
        visibility?: string | undefined;
    }) => SVGPathElement;
    createRect: (props: {
        document?: Document | undefined;
        x?: string | number | undefined;
        y?: string | number | undefined;
        width?: string | number | undefined;
        height?: string | number | undefined;
        rx?: string | number | undefined;
        ry?: string | number | undefined;
        id?: string | undefined;
        classes?: string | undefined;
        style?: string | undefined;
        pathLength?: string | number | undefined;
        stroke?: string | undefined;
        strokeWidth?: string | number | undefined;
        strokeOpacity?: string | number | undefined;
        strokeLinecap?: string | undefined;
        strokeLinejoin?: string | undefined;
        strokeDasharray?: string | undefined;
        strokeDashoffset?: string | number | undefined;
        strokeMiterlimit?: string | number | undefined;
        fill?: string | undefined;
        fillOpacity?: string | number | undefined;
        fillRule?: string | undefined;
        filter?: string | undefined;
        mask?: string | undefined;
        transform?: string | undefined;
        vectorEffect?: string | undefined;
        shapeRendering?: string | undefined;
        clipPath?: string | undefined;
        clipRule?: string | undefined;
        opacity?: string | number | undefined;
        visibility?: string | undefined;
    }) => SVGRectElement;
    createCircle: (props: {
        document?: Document | undefined;
        cx?: string | number | undefined;
        cy?: string | number | undefined;
        r?: string | number | undefined;
        id?: string | undefined;
        classes?: string | undefined;
        style?: string | undefined;
        pathLength?: string | number | undefined;
        stroke?: string | undefined;
        strokeWidth?: string | number | undefined;
        strokeOpacity?: string | number | undefined;
        strokeLinecap?: string | undefined;
        strokeLinejoin?: string | undefined;
        strokeDasharray?: string | undefined;
        strokeDashoffset?: string | number | undefined;
        strokeMiterlimit?: string | number | undefined;
        fill?: string | undefined;
        fillOpacity?: string | number | undefined;
        fillRule?: string | undefined;
        filter?: string | undefined;
        mask?: string | undefined;
        transform?: string | undefined;
        vectorEffect?: string | undefined;
        shapeRendering?: string | undefined;
        clipPath?: string | undefined;
        clipRule?: string | undefined;
        opacity?: string | number | undefined;
        visibility?: string | undefined;
    }) => SVGCircleElement;
    createEllipse: (props: {
        document?: Document | undefined;
        cx?: string | number | undefined;
        cy?: string | number | undefined;
        rx?: string | number | undefined;
        ry?: string | number | undefined;
        id?: string | undefined;
        classes?: string | undefined;
        style?: string | undefined;
        pathLength?: string | number | undefined;
        stroke?: string | undefined;
        strokeWidth?: string | number | undefined;
        strokeOpacity?: string | number | undefined;
        strokeLinecap?: string | undefined;
        strokeLinejoin?: string | undefined;
        strokeDasharray?: string | undefined;
        strokeDashoffset?: string | number | undefined;
        strokeMiterlimit?: string | number | undefined;
        fill?: string | undefined;
        fillOpacity?: string | number | undefined;
        fillRule?: string | undefined;
        filter?: string | undefined;
        mask?: string | undefined;
        transform?: string | undefined;
        vectorEffect?: string | undefined;
        shapeRendering?: string | undefined;
        clipPath?: string | undefined;
        clipRule?: string | undefined;
        opacity?: string | number | undefined;
        visibility?: string | undefined;
    }) => SVGEllipseElement;
    createLine: (props: {
        document?: Document | undefined;
        x1?: string | number | undefined;
        y1?: string | number | undefined;
        x2?: string | number | undefined;
        y2?: string | number | undefined;
        id?: string | undefined;
        classes?: string | undefined;
        style?: string | undefined;
        pathLength?: string | number | undefined;
        stroke?: string | undefined;
        strokeWidth?: string | number | undefined;
        strokeOpacity?: string | number | undefined;
        strokeLinecap?: string | undefined;
        strokeLinejoin?: string | undefined;
        strokeDasharray?: string | undefined;
        strokeDashoffset?: string | number | undefined;
        strokeMiterlimit?: string | number | undefined;
        fill?: string | undefined;
        fillOpacity?: string | number | undefined;
        fillRule?: string | undefined;
        filter?: string | undefined;
        mask?: string | undefined;
        transform?: string | undefined;
        vectorEffect?: string | undefined;
        shapeRendering?: string | undefined;
        clipPath?: string | undefined;
        clipRule?: string | undefined;
        opacity?: string | number | undefined;
        visibility?: string | undefined;
    }) => SVGLineElement;
    SVG_NAMESPACE: "http://www.w3.org/2000/svg";
    XMLNS_NAMESPACE: "http://www.w3.org/2000/xmlns/";
    DEFAULT_DECIMAL_PLACES: 2;
    createSVG: (props: {
        width: number;
        height: number;
        document?: Document | undefined;
    }) => SVGSVGElement;
    createSVGFromString: (props: {
        document?: Document | undefined;
        svg: string;
    }) => SVGSVGElement;
    getSVGAsString: ($svg: SVGSVGElement) => string;
    setAttributes: ($svgElement: SVGElement, attr: [string, string | number | undefined][]) => void;
};
declare global {
    interface Window {
        mzSVG: typeof api;
    }
}
export * from './main/core';
export * from './main/shapes/primitive-shapes';
export * from './main/io-browser';
export * from './main/shapes/star-shapes';
export * from './main/shapes/shape-paths';
